const quizzData = [
  {
    id: 1,
    category: "Python",
    question: "What is the output of `print(2 ** 3)`?",
    options: [4, 6, 8, 9],
    correctAnswer: 8,
    difficulty: "Easy",
  },
  {
    id: 2,
    category: "Java",
    question: "Which keyword is used to inherit a class in Java?",
    options: ["extends", "implements", "inherits", "final"],
    correctAnswer: "extends",
    difficulty: "Easy",
  },
  {
    id: 3,
    category: "Web Development",
    question: "What does HTML stand for?",
    options: [
      "HyperText Markup Language",
      "Hyperlink Text Module",
      "Home Tool Markup Language",
      "None of these",
    ],
    correctAnswer: "HyperText Markup Language",
    difficulty: "Easy",
  },
  {
    id: 4,
    category: "Data Structures",
    question: "Which data structure uses FIFO (First In First Out)?",
    options: ["Stack", "Queue", "Linked List", "Tree"],
    correctAnswer: "Queue",
    difficulty: "Medium",
  },
  {
    id: 5,
    category: "C++",
    question: "Which of the following is a correct comment in C++?",
    options: ["// Single line", "/** Multiline */", "# This", "; Comment"],
    correctAnswer: "// Single line",
    difficulty: "Easy",
  },
  {
    id: 6,
    category: "Python",
    question: "What is the output of `len([10, 20, 30])`?",
    options: [2, 3, 4, "Error"],
    correctAnswer: 3,
    difficulty: "Easy",
  },
  {
    id: 7,
    category: "JavaScript",
    question: "Which company developed JavaScript?",
    options: ["Microsoft", "Netscape", "Sun Microsystems", "Google"],
    correctAnswer: "Netscape",
    difficulty: "Medium",
  },
  {
    id: 8,
    category: "Algorithms",
    question: "What is the time complexity of binary search?",
    options: ["O(n)", "O(log n)", "O(n^2)", "O(n log n)"],
    correctAnswer: "O(log n)",
    difficulty: "Medium",
  },
  {
    id: 9,
    category: "OOP",
    question: "Which principle is NOT part of Object-Oriented Programming?",
    options: ["Encapsulation", "Inheritance", "Polymorphism", "Compilation"],
    correctAnswer: "Compilation",
    difficulty: "Medium",
  },
  {
    id: 10,
    category: "Databases",
    question: "What does SQL stand for?",
    options: [
      "Structured Query Language",
      "Simple Query Logic",
      "Sequential Query Language",
      "Systematic Query Language",
    ],
    correctAnswer: "Structured Query Language",
    difficulty: "Easy",
  },
  {
    id: 11,
    category: "Web Development",
    question: "Which tag is used to define an image in HTML?",
    options: ["<img>", "<picture>", "<media>", "<src>"],
    correctAnswer: "<img>",
    difficulty: "Easy",
  },
  {
    id: 12,
    category: "JavaScript",
    question: "What is the correct way to declare a variable in JavaScript?",
    options: ["let", "var", "const", "All of the above"],
    correctAnswer: "All of the above",
    difficulty: "Easy",
  },
  {
    id: 13,
    category: "Python",
    question: "Which method is used to add an element to a list in Python?",
    options: ["append()", "add()", "insert()", "push()"],
    correctAnswer: "append()",
    difficulty: "Easy",
  },
  {
    id: 14,
    category: "Java",
    question: "What is the default value of a boolean variable in Java?",
    options: ["true", "false", "0", "undefined"],
    correctAnswer: "false",
    difficulty: "Easy",
  },
  {
    id: 15,
    category: "Operating Systems",
    question: "What is the main purpose of an operating system?",
    options: ["Run hardware", "Manage software resources", "Both", "None"],
    correctAnswer: "Both",
    difficulty: "Medium",
  },
  {
    id: 16,
    category: "Algorithms",
    question: "What is the Big-O complexity of bubble sort in the worst case?",
    options: ["O(n)", "O(n^2)", "O(log n)", "O(n log n)"],
    correctAnswer: "O(n^2)",
    difficulty: "Hard",
  },
  {
    id: 17,
    category: "Data Structures",
    question: "Which data structure is best for implementing LRU cache?",
    options: ["Queue", "Stack", "Hash Map", "Linked HashMap"],
    correctAnswer: "Linked HashMap",
    difficulty: "Hard",
  },
  {
    id: 18,
    category: "Web Development",
    question: "Which CSS property controls the text size?",
    options: ["font-style", "text-size", "font-size", "text-transform"],
    correctAnswer: "font-size",
    difficulty: "Easy",
  },
  {
    id: 19,
    category: "Networking",
    question: "What is the full form of IP in networking?",
    options: [
      "Internet Protocol",
      "Internal Protocol",
      "Intranet Provider",
      "Integrated Protocol",
    ],
    correctAnswer: "Internet Protocol",
    difficulty: "Easy",
  },
  {
    id: 20,
    category: "Python",
    question: "What is the difference between `is` and `==` in Python?",
    options: [
      "is compares references, == compares values",
      "Both are same",
      "is compares strings",
      "None",
    ],
    correctAnswer: "is compares references, == compares values",
    difficulty: "Medium",
  },
];

export default quizzData;
